import { Card, Container } from "@/ui";
import Layout from "../layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Avero || Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="h-96 bg-slate-600">
            <h1>sdasdsd</h1>
            <Card className="">sadasd</Card>
          </div>
        </Container>
      </main>
    </>
  );
}
